name: '.NET Test report'
on:
  workflow_run:
    workflows: ['.NET']
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JUnit
          path: |
            .test-results/unit/TestResults.xml
            .test-results/integration/TestResults.xml
          reporter: java-junit
