name: TEST WORKFLOW
on: 
  workflow_run:
    workflows: 
      - ".NET"
      - "Docker image"
    types: 
      - completed
  
jobs:
  TestWorkflow:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.event.workflow_run.head_branch }}
       - name: ECHO
         run: echo "test"