name: TEST WORKFLOW
on: 
  workflow_run:
    workflows: [".NET"]
    types: [completed]
jobs:
  TestWorkflow:
    runs-on: ubuntu-latest
    environment: testing
    steps:
        - uses: actions/checkout@v3
        - name: Build
          run: echo "test"