name: TEST WORKFLOW
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  TestWorkflow:
    runs-on: ubuntu-latest
    environment: testing
    steps:
        - uses: actions/checkout@v3
        - name: Build
          run: echo "test"